# Generated by Django 2.1.11 on 2019-08-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190822_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparar',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reparar',
            name='country',
        ),
        migrations.RemoveField(
            model_name='reparar',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='reparar',
            name='program',
        ),
    ]
