# Generated by Django 2.1.11 on 2019-08-23 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
