# Generated by Django 2.1.11 on 2019-08-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typeuser',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
