# Generated by Django 2.1.11 on 2019-08-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_typeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Please enter your Phone', max_length=300, null=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='suscription',
            field=models.BooleanField(default=True, verbose_name='suscription newsletter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeuser',
            field=models.CharField(choices=[('1', 'Candidates'), ('2', 'Employer')], max_length=10, null=True, verbose_name='Type User'),
        ),
    ]
